# Generated by Django 5.0.4 on 2024-05-19 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='nro_apartamento',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apartamento',
            field=models.ManyToManyField(blank=True, related_name='pe_apto', to='core.apartamento'),
        ),
    ]
