# Generated by Django 5.0.4 on 2024-06-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_fin',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha Finalización Encuesta'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha Inicio Encuesta'),
        ),
    ]
