# Generated by Django 5.0.4 on 2024-06-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_apartamento_nro_apartamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Encuesta',
            fields=[
                ('id_estado', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('abreviatura', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Estado Encuesta',
            },
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encu_estado', to='core.estado_encuesta'),
        ),
    ]
