# Generated by Django 5.0.4 on 2024-06-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_encuesta_fecha_fin_alter_encuesta_fecha_inicio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartamento',
            unique_together={('nro_apartamento', 'nro_torre')},
        ),
    ]
